server:
  port: 8089
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service-route
            uri: lb://order-service
            predicates:
              - Path=/orders/**
          - id: customer-service-route
            uri: lb://customer-service
            predicates:
              - Path=/customer/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/